// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRcG4mCgDwjvGKdzyFdGy3X5muwEPmeM4',
    appId: '1:465155784135:web:39b92b47e93301b2b9ede2',
    messagingSenderId: '465155784135',
    projectId: 'tkm-mini-proj',
    authDomain: 'tkm-mini-proj.firebaseapp.com',
    storageBucket: 'tkm-mini-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpE4m-iwU3t_gCJ5Ag9d8tmva6SU-XP94',
    appId: '1:465155784135:android:0fd71243761e3f05b9ede2',
    messagingSenderId: '465155784135',
    projectId: 'tkm-mini-proj',
    storageBucket: 'tkm-mini-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWj0E8__-ozZRNK_QZU3bpXuBlkhugyyM',
    appId: '1:465155784135:ios:910fca621757fe8bb9ede2',
    messagingSenderId: '465155784135',
    projectId: 'tkm-mini-proj',
    storageBucket: 'tkm-mini-proj.appspot.com',
    iosClientId: '465155784135-78g2t9leacd2r79usc48t93i63pektv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWj0E8__-ozZRNK_QZU3bpXuBlkhugyyM',
    appId: '1:465155784135:ios:910fca621757fe8bb9ede2',
    messagingSenderId: '465155784135',
    projectId: 'tkm-mini-proj',
    storageBucket: 'tkm-mini-proj.appspot.com',
    iosClientId: '465155784135-78g2t9leacd2r79usc48t93i63pektv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );
}
