// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtB1p8DNXnTC0ZoqlqXHBS0inxUPS5BYk',
    appId: '1:461317471469:web:f682120fac9aaa703ba0e4',
    messagingSenderId: '461317471469',
    projectId: 'examseatingarrangement-5ea4d',
    authDomain: 'examseatingarrangement-5ea4d.firebaseapp.com',
    storageBucket: 'examseatingarrangement-5ea4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfCNtn0XIGEEDiM0DwGtN7SWypvv-wMOI',
    appId: '1:461317471469:android:a616ca268fda498d3ba0e4',
    messagingSenderId: '461317471469',
    projectId: 'examseatingarrangement-5ea4d',
    storageBucket: 'examseatingarrangement-5ea4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTNOxJgLHiQ9xVrCHZ3gS9yGm-7-8tiqI',
    appId: '1:461317471469:ios:82e5819a4f8be5973ba0e4',
    messagingSenderId: '461317471469',
    projectId: 'examseatingarrangement-5ea4d',
    storageBucket: 'examseatingarrangement-5ea4d.appspot.com',
    iosClientId: '461317471469-rgvef8tm67ih1ni188pkhjcpuptln0pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTNOxJgLHiQ9xVrCHZ3gS9yGm-7-8tiqI',
    appId: '1:461317471469:ios:82e5819a4f8be5973ba0e4',
    messagingSenderId: '461317471469',
    projectId: 'examseatingarrangement-5ea4d',
    storageBucket: 'examseatingarrangement-5ea4d.appspot.com',
    iosClientId: '461317471469-rgvef8tm67ih1ni188pkhjcpuptln0pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );
}
