// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-fo2L3VBGLX9ZOvjx3l9jOk2j4ME9jY',
    appId: '1:1033252063252:web:27651b00ad199fa424ff01',
    messagingSenderId: '1033252063252',
    projectId: 'pro1-1f747',
    authDomain: 'pro1-1f747.firebaseapp.com',
    storageBucket: 'pro1-1f747.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktUFjnQgnXQOgyGD7zBZ8t3bw5LuiGZQ',
    appId: '1:1033252063252:android:0c8741714b1a3fd324ff01',
    messagingSenderId: '1033252063252',
    projectId: 'pro1-1f747',
    storageBucket: 'pro1-1f747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBijvBU7LmcuVz1frlJ1SpdkkRU956c1s',
    appId: '1:1033252063252:ios:d3e9564823daa05824ff01',
    messagingSenderId: '1033252063252',
    projectId: 'pro1-1f747',
    storageBucket: 'pro1-1f747.appspot.com',
    iosClientId: '1033252063252-7r6vkatlqkom6lgovmcufqb8a56m2m3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBijvBU7LmcuVz1frlJ1SpdkkRU956c1s',
    appId: '1:1033252063252:ios:d3e9564823daa05824ff01',
    messagingSenderId: '1033252063252',
    projectId: 'pro1-1f747',
    storageBucket: 'pro1-1f747.appspot.com',
    iosClientId: '1033252063252-7r6vkatlqkom6lgovmcufqb8a56m2m3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.submini',
  );
}
